// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/purchase.proto

package purchase

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Purchase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_proto_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *Purchase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Purchase) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Purchase) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Purchase) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Purchase) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Purchase) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CreatePurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePurchaseRequest) Reset() {
	*x = CreatePurchaseRequest{}
	mi := &file_proto_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseRequest) ProtoMessage() {}

func (x *CreatePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseRequest.ProtoReflect.Descriptor instead.
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePurchaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePurchaseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreatePurchaseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseRequest) Reset() {
	*x = GetPurchaseRequest{}
	mi := &file_proto_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseRequest) ProtoMessage() {}

func (x *GetPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseRequest.ProtoReflect.Descriptor instead.
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *GetPurchaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPurchasesRequest) Reset() {
	*x = GetUserPurchasesRequest{}
	mi := &file_proto_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPurchasesRequest) ProtoMessage() {}

func (x *GetUserPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPurchasesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPurchasesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*Purchase            `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPurchasesResponse) Reset() {
	*x = GetUserPurchasesResponse{}
	mi := &file_proto_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPurchasesResponse) ProtoMessage() {}

func (x *GetUserPurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPurchasesResponse.ProtoReflect.Descriptor instead.
func (*GetUserPurchasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPurchasesResponse) GetPurchases() []*Purchase {
	if x != nil {
		return x.Purchases
	}
	return nil
}

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_proto_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_proto_purchase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *CheckAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

type PurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchase      *Purchase              `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_proto_purchase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{7}
}

func (x *PurchaseResponse) GetPurchase() *Purchase {
	if x != nil {
		return x.Purchase
	}
	return nil
}

var File_proto_purchase_proto protoreflect.FileDescriptor

const file_proto_purchase_proto_rawDesc = "" +
	"\n" +
	"\x14proto/purchase.proto\x12\bpurchase\x1a\x1bbuf/validate/validate.proto\"\xa7\x01\n" +
	"\bPurchase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\"\x87\x01\n" +
	"\x15CreatePurchaseRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12$\n" +
	"\tcourse_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bcourseId\x12&\n" +
	"\x06amount\x18\x03 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\"-\n" +
	"\x12GetPurchaseRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\";\n" +
	"\x17GetUserPurchasesRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"L\n" +
	"\x18GetUserPurchasesResponse\x120\n" +
	"\tpurchases\x18\x01 \x03(\v2\x12.purchase.PurchaseR\tpurchases\"\\\n" +
	"\x12CheckAccessRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12$\n" +
	"\tcourse_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bcourseId\"4\n" +
	"\x13CheckAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\"B\n" +
	"\x10PurchaseResponse\x12.\n" +
	"\bpurchase\x18\x01 \x01(\v2\x12.purchase.PurchaseR\bpurchase2\xd0\x02\n" +
	"\x0fPurchaseService\x12M\n" +
	"\x0eCreatePurchase\x12\x1f.purchase.CreatePurchaseRequest\x1a\x1a.purchase.PurchaseResponse\x12G\n" +
	"\vGetPurchase\x12\x1c.purchase.GetPurchaseRequest\x1a\x1a.purchase.PurchaseResponse\x12Y\n" +
	"\x10GetUserPurchases\x12!.purchase.GetUserPurchasesRequest\x1a\".purchase.GetUserPurchasesResponse\x12J\n" +
	"\vCheckAccess\x12\x1c.purchase.CheckAccessRequest\x1a\x1d.purchase.CheckAccessResponseB$Z\"artplatform/backend/proto/purchaseb\x06proto3"

var (
	file_proto_purchase_proto_rawDescOnce sync.Once
	file_proto_purchase_proto_rawDescData []byte
)

func file_proto_purchase_proto_rawDescGZIP() []byte {
	file_proto_purchase_proto_rawDescOnce.Do(func() {
		file_proto_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)))
	})
	return file_proto_purchase_proto_rawDescData
}

var file_proto_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_purchase_proto_goTypes = []any{
	(*Purchase)(nil),                 // 0: purchase.Purchase
	(*CreatePurchaseRequest)(nil),    // 1: purchase.CreatePurchaseRequest
	(*GetPurchaseRequest)(nil),       // 2: purchase.GetPurchaseRequest
	(*GetUserPurchasesRequest)(nil),  // 3: purchase.GetUserPurchasesRequest
	(*GetUserPurchasesResponse)(nil), // 4: purchase.GetUserPurchasesResponse
	(*CheckAccessRequest)(nil),       // 5: purchase.CheckAccessRequest
	(*CheckAccessResponse)(nil),      // 6: purchase.CheckAccessResponse
	(*PurchaseResponse)(nil),         // 7: purchase.PurchaseResponse
}
var file_proto_purchase_proto_depIdxs = []int32{
	0, // 0: purchase.GetUserPurchasesResponse.purchases:type_name -> purchase.Purchase
	0, // 1: purchase.PurchaseResponse.purchase:type_name -> purchase.Purchase
	1, // 2: purchase.PurchaseService.CreatePurchase:input_type -> purchase.CreatePurchaseRequest
	2, // 3: purchase.PurchaseService.GetPurchase:input_type -> purchase.GetPurchaseRequest
	3, // 4: purchase.PurchaseService.GetUserPurchases:input_type -> purchase.GetUserPurchasesRequest
	5, // 5: purchase.PurchaseService.CheckAccess:input_type -> purchase.CheckAccessRequest
	7, // 6: purchase.PurchaseService.CreatePurchase:output_type -> purchase.PurchaseResponse
	7, // 7: purchase.PurchaseService.GetPurchase:output_type -> purchase.PurchaseResponse
	4, // 8: purchase.PurchaseService.GetUserPurchases:output_type -> purchase.GetUserPurchasesResponse
	6, // 9: purchase.PurchaseService.CheckAccess:output_type -> purchase.CheckAccessResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_purchase_proto_init() }
func file_proto_purchase_proto_init() {
	if File_proto_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_proto_goTypes,
		DependencyIndexes: file_proto_purchase_proto_depIdxs,
		MessageInfos:      file_proto_purchase_proto_msgTypes,
	}.Build()
	File_proto_purchase_proto = out.File
	file_proto_purchase_proto_goTypes = nil
	file_proto_purchase_proto_depIdxs = nil
}
