package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"artplatform/backend/api/graphql/generated"
	"artplatform/backend/api/graphql/generated/model"
	authpb "artplatform/backend/proto/auth"
	"context"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Register(ctx, &authpb.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
		Role:     input.Role,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		UserID: resp.UserId,
		Token:  resp.Token,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Login(ctx, &authpb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		UserID: resp.UserId,
		Token:  resp.Token,
	}, nil
}

// GetCurrentUser is the resolver for the getCurrentUser field.
func (r *queryResolver) GetCurrentUser(ctx context.Context) (*model.User, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.AuthClient.GetUser(ctx, &authpb.GetUserRequest{UserId: userID})
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:    resp.UserId,
		Email: resp.Email,
		Role:  resp.Role,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
