package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"artplatform/backend/api/graphql/generated/model"
	coursepb "artplatform/backend/proto/course"
	"context"
)

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.CreateCourseInput) (*model.Course, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.CourseClient.CreateCourse(ctx, &coursepb.CreateCourseRequest{
		AuthorId:    userID,
		Title:       input.Title,
		Description: input.Description,
		Price:       input.Price,
	})
	if err != nil {
		return nil, err
	}
	return toCourseModel(resp.Course), nil
}

// UpdateCourse is the resolver for the updateCourse field.
func (r *mutationResolver) UpdateCourse(ctx context.Context, input model.UpdateCourseInput) (*model.Course, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.CourseClient.UpdateCourse(ctx, &coursepb.UpdateCourseRequest{
		Id:          input.ID,
		RequesterId: userID,
		Title:       input.Title,
		Description: input.Description,
		Price:       input.Price,
		Status:      input.Status,
	})
	if err != nil {
		return nil, err
	}
	return toCourseModel(resp.Course), nil
}

// DeleteCourse is the resolver for the deleteCourse field.
func (r *mutationResolver) DeleteCourse(ctx context.Context, id string) (bool, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	resp, err := r.CourseClient.DeleteCourse(ctx, &coursepb.DeleteCourseRequest{
		Id:          id,
		RequesterId: userID,
	})
	if err != nil {
		return false, err
	}
	return resp.Success, nil
}

// PublishCourse is the resolver for the publishCourse field.
func (r *mutationResolver) PublishCourse(ctx context.Context, id string) (*model.Course, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.CourseClient.PublishCourse(ctx, &coursepb.PublishCourseRequest{
		Id:          id,
		RequesterId: userID,
	})
	if err != nil {
		return nil, err
	}
	return toCourseModel(resp.Course), nil
}

// GetCourse is the resolver for the getCourse field.
func (r *queryResolver) GetCourse(ctx context.Context, id string) (*model.Course, error) {
	resp, err := r.CourseClient.GetCourse(ctx, &coursepb.GetCourseRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return toCourseModel(resp.Course), nil
}

// GetCourses is the resolver for the getCourses field.
func (r *queryResolver) GetCourses(ctx context.Context, authorID *string) ([]*model.Course, error) {
	req := &coursepb.GetCoursesRequest{}
	if authorID != nil {
		req.AuthorId = *authorID
	}
	resp, err := r.CourseClient.GetCourses(ctx, req)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Course, len(resp.Courses))
	for i, c := range resp.Courses {
		result[i] = toCourseModel(c)
	}
	return result, nil
}
