package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"artplatform/backend/api/graphql/generated/model"
	mediapb "artplatform/backend/proto/media"
	"context"
	"encoding/base64"
)

// UploadMedia is the resolver for the uploadMedia field.
func (r *mutationResolver) UploadMedia(ctx context.Context, input model.UploadMediaInput) (*model.Media, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	content, err := base64.StdEncoding.DecodeString(input.ContentBase64)
	if err != nil {
		return nil, err
	}

	var courseID string
	if input.CourseID != nil {
		courseID = *input.CourseID
	}

	resp, err := r.MediaClient.UploadMedia(ctx, &mediapb.UploadMediaRequest{
		OwnerId:     userID,
		CourseId:    courseID,
		FileName:    input.FileName,
		ContentType: input.ContentType,
		Content:     content,
	})
	if err != nil {
		return nil, err
	}
	return toMediaModel(resp.Media), nil
}

// GetMedia is the resolver for the getMedia field.
func (r *queryResolver) GetMedia(ctx context.Context, id string) (*model.Media, error) {
	resp, err := r.MediaClient.GetMedia(ctx, &mediapb.GetMediaRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return toMediaModel(resp.Media), nil
}

// GetPresignedURL is the resolver for the getPresignedURL field.
func (r *queryResolver) GetPresignedURL(ctx context.Context, mediaID string) (*model.PresignedURL, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.MediaClient.GetPresignedURL(ctx, &mediapb.GetPresignedURLRequest{
		Id:          mediaID,
		RequesterId: userID,
	})
	if err != nil {
		return nil, err
	}
	return &model.PresignedURL{
		URL:  resp.Url,
		Type: resp.Type,
	}, nil
}
