package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"artplatform/backend/api/graphql/generated/model"
	purchasepb "artplatform/backend/proto/purchase"
	"context"
)

// PurchaseCourse is the resolver for the purchaseCourse field.
func (r *mutationResolver) PurchaseCourse(ctx context.Context, courseID string, amount float64) (*model.Purchase, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PurchaseClient.CreatePurchase(ctx, &purchasepb.CreatePurchaseRequest{
		UserId:   userID,
		CourseId: courseID,
		Amount:   amount,
	})
	if err != nil {
		return nil, err
	}
	return toPurchaseModel(resp.Purchase), nil
}

// GetPurchase is the resolver for the getPurchase field.
func (r *queryResolver) GetPurchase(ctx context.Context, id string) (*model.Purchase, error) {
	resp, err := r.PurchaseClient.GetPurchase(ctx, &purchasepb.GetPurchaseRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return toPurchaseModel(resp.Purchase), nil
}

// GetUserPurchases is the resolver for the getUserPurchases field.
func (r *queryResolver) GetUserPurchases(ctx context.Context) ([]*model.Purchase, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PurchaseClient.GetUserPurchases(ctx, &purchasepb.GetUserPurchasesRequest{UserId: userID})
	if err != nil {
		return nil, err
	}
	result := make([]*model.Purchase, len(resp.Purchases))
	for i, p := range resp.Purchases {
		result[i] = toPurchaseModel(p)
	}
	return result, nil
}

// CheckCourseAccess is the resolver for the checkCourseAccess field.
func (r *queryResolver) CheckCourseAccess(ctx context.Context, courseID string) (*model.CheckAccessResult, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PurchaseClient.CheckAccess(ctx, &purchasepb.CheckAccessRequest{
		UserId:   userID,
		CourseId: courseID,
	})
	if err != nil {
		return nil, err
	}
	return &model.CheckAccessResult{HasAccess: resp.HasAccess}, nil
}
