syntax = "proto3";

package payment;

option go_package = "artplatform/backend/proto/payment";

import "buf/validate/validate.proto";

service PaymentService {
  rpc ProcessPayment(ProcessPaymentRequest) returns (TransactionResponse);
  rpc GetTransaction(GetTransactionRequest) returns (TransactionResponse);
}

message Transaction {
  string id = 1;
  string user_id = 2;
  string course_id = 3;
  double amount = 4;
  string status = 5;
}

message ProcessPaymentRequest {
  string user_id   = 1 [(buf.validate.field).string.min_len = 1];
  string course_id = 2 [(buf.validate.field).string.min_len = 1];
  double amount    = 3 [(buf.validate.field).double.gt = 0];
}

message GetTransactionRequest {
  string id = 1 [(buf.validate.field).string.min_len = 1];
}

message TransactionResponse {
  Transaction transaction = 1;
}