// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/media.proto

package media

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	OriginalKey   string                 `protobuf:"bytes,7,opt,name=original_key,json=originalKey,proto3" json:"original_key,omitempty"`
	PreviewKey    string                 `protobuf:"bytes,8,opt,name=preview_key,json=previewKey,proto3" json:"preview_key,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaFile) Reset() {
	*x = MediaFile{}
	mi := &file_proto_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFile) ProtoMessage() {}

func (x *MediaFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFile.ProtoReflect.Descriptor instead.
func (*MediaFile) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaFile) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MediaFile) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *MediaFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaFile) GetOriginalKey() string {
	if x != nil {
		return x.OriginalKey
	}
	return ""
}

func (x *MediaFile) GetPreviewKey() string {
	if x != nil {
		return x.PreviewKey
	}
	return ""
}

func (x *MediaFile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_proto_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UploadMediaRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UploadMediaRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadMediaRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadMediaRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_proto_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPresignedURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedURLRequest) Reset() {
	*x = GetPresignedURLRequest{}
	mi := &file_proto_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedURLRequest) ProtoMessage() {}

func (x *GetPresignedURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedURLRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetPresignedURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPresignedURLRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type GetPresignedURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "original" | "preview"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedURLResponse) Reset() {
	*x = GetPresignedURLResponse{}
	mi := &file_proto_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedURLResponse) ProtoMessage() {}

func (x *GetPresignedURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedURLResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetPresignedURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetPresignedURLResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaFile             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_proto_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{5}
}

func (x *MediaResponse) GetMedia() *MediaFile {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_proto_media_proto protoreflect.FileDescriptor

const file_proto_media_proto_rawDesc = "" +
	"\n" +
	"\x11proto/media.proto\x12\x05media\x1a\x1bbuf/validate/validate.proto\"\x83\x02\n" +
	"\tMediaFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12!\n" +
	"\foriginal_key\x18\a \x01(\tR\voriginalKey\x12\x1f\n" +
	"\vpreview_key\x18\b \x01(\tR\n" +
	"previewKey\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\xf6\x01\n" +
	"\x12UploadMediaRequest\x12\"\n" +
	"\bowner_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aownerId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12$\n" +
	"\tfile_name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfileName\x12V\n" +
	"\fcontent_type\x18\x04 \x01(\tB3\xbaH0r.R\n" +
	"image/jpegR\timage/pngR\n" +
	"image/webpR\timage/gifR\vcontentType\x12!\n" +
	"\acontent\x18\x05 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\acontent\"*\n" +
	"\x0fGetMediaRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"]\n" +
	"\x16GetPresignedURLRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12*\n" +
	"\frequester_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vrequesterId\"?\n" +
	"\x17GetPresignedURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"7\n" +
	"\rMediaResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaFileR\x05media2\xda\x01\n" +
	"\fMediaService\x12>\n" +
	"\vUploadMedia\x12\x19.media.UploadMediaRequest\x1a\x14.media.MediaResponse\x128\n" +
	"\bGetMedia\x12\x16.media.GetMediaRequest\x1a\x14.media.MediaResponse\x12P\n" +
	"\x0fGetPresignedURL\x12\x1d.media.GetPresignedURLRequest\x1a\x1e.media.GetPresignedURLResponseB!Z\x1fartplatform/backend/proto/mediab\x06proto3"

var (
	file_proto_media_proto_rawDescOnce sync.Once
	file_proto_media_proto_rawDescData []byte
)

func file_proto_media_proto_rawDescGZIP() []byte {
	file_proto_media_proto_rawDescOnce.Do(func() {
		file_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_proto_rawDesc), len(file_proto_media_proto_rawDesc)))
	})
	return file_proto_media_proto_rawDescData
}

var file_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_media_proto_goTypes = []any{
	(*MediaFile)(nil),               // 0: media.MediaFile
	(*UploadMediaRequest)(nil),      // 1: media.UploadMediaRequest
	(*GetMediaRequest)(nil),         // 2: media.GetMediaRequest
	(*GetPresignedURLRequest)(nil),  // 3: media.GetPresignedURLRequest
	(*GetPresignedURLResponse)(nil), // 4: media.GetPresignedURLResponse
	(*MediaResponse)(nil),           // 5: media.MediaResponse
}
var file_proto_media_proto_depIdxs = []int32{
	0, // 0: media.MediaResponse.media:type_name -> media.MediaFile
	1, // 1: media.MediaService.UploadMedia:input_type -> media.UploadMediaRequest
	2, // 2: media.MediaService.GetMedia:input_type -> media.GetMediaRequest
	3, // 3: media.MediaService.GetPresignedURL:input_type -> media.GetPresignedURLRequest
	5, // 4: media.MediaService.UploadMedia:output_type -> media.MediaResponse
	5, // 5: media.MediaService.GetMedia:output_type -> media.MediaResponse
	4, // 6: media.MediaService.GetPresignedURL:output_type -> media.GetPresignedURLResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_media_proto_init() }
func file_proto_media_proto_init() {
	if File_proto_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_proto_rawDesc), len(file_proto_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_proto_goTypes,
		DependencyIndexes: file_proto_media_proto_depIdxs,
		MessageInfos:      file_proto_media_proto_msgTypes,
	}.Build()
	File_proto_media_proto = out.File
	file_proto_media_proto_goTypes = nil
	file_proto_media_proto_depIdxs = nil
}
