// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/activity.proto

package activity

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ViewCount     int64                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	PurchaseCount int64                  `protobuf:"varint,3,opt,name=purchase_count,json=purchaseCount,proto3" json:"purchase_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseStats) Reset() {
	*x = CourseStats{}
	mi := &file_proto_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseStats) ProtoMessage() {}

func (x *CourseStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseStats.ProtoReflect.Descriptor instead.
func (*CourseStats) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{0}
}

func (x *CourseStats) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseStats) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *CourseStats) GetPurchaseCount() int64 {
	if x != nil {
		return x.PurchaseCount
	}
	return 0
}

type GetCourseStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseStatsRequest) Reset() {
	*x = GetCourseStatsRequest{}
	mi := &file_proto_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseStatsRequest) ProtoMessage() {}

func (x *GetCourseStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{1}
}

func (x *GetCourseStatsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type RecordViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewRequest) Reset() {
	*x = RecordViewRequest{}
	mi := &file_proto_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewRequest) ProtoMessage() {}

func (x *RecordViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewRequest.ProtoReflect.Descriptor instead.
func (*RecordViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{2}
}

func (x *RecordViewRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type RecordViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordViewResponse) Reset() {
	*x = RecordViewResponse{}
	mi := &file_proto_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewResponse) ProtoMessage() {}

func (x *RecordViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewResponse.ProtoReflect.Descriptor instead.
func (*RecordViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{3}
}

func (x *RecordViewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CourseStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *CourseStats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseStatsResponse) Reset() {
	*x = CourseStatsResponse{}
	mi := &file_proto_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseStatsResponse) ProtoMessage() {}

func (x *CourseStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseStatsResponse.ProtoReflect.Descriptor instead.
func (*CourseStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_activity_proto_rawDescGZIP(), []int{4}
}

func (x *CourseStatsResponse) GetStats() *CourseStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_activity_proto protoreflect.FileDescriptor

const file_proto_activity_proto_rawDesc = "" +
	"\n" +
	"\x14proto/activity.proto\x12\bactivity\x1a\x1bbuf/validate/validate.proto\"p\n" +
	"\vCourseStats\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x03R\tviewCount\x12%\n" +
	"\x0epurchase_count\x18\x03 \x01(\x03R\rpurchaseCount\"=\n" +
	"\x15GetCourseStatsRequest\x12$\n" +
	"\tcourse_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bcourseId\"9\n" +
	"\x11RecordViewRequest\x12$\n" +
	"\tcourse_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bcourseId\".\n" +
	"\x12RecordViewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x13CourseStatsResponse\x12+\n" +
	"\x05stats\x18\x01 \x01(\v2\x15.activity.CourseStatsR\x05stats2\xac\x01\n" +
	"\x0fActivityService\x12P\n" +
	"\x0eGetCourseStats\x12\x1f.activity.GetCourseStatsRequest\x1a\x1d.activity.CourseStatsResponse\x12G\n" +
	"\n" +
	"RecordView\x12\x1b.activity.RecordViewRequest\x1a\x1c.activity.RecordViewResponseB$Z\"artplatform/backend/proto/activityb\x06proto3"

var (
	file_proto_activity_proto_rawDescOnce sync.Once
	file_proto_activity_proto_rawDescData []byte
)

func file_proto_activity_proto_rawDescGZIP() []byte {
	file_proto_activity_proto_rawDescOnce.Do(func() {
		file_proto_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_activity_proto_rawDesc), len(file_proto_activity_proto_rawDesc)))
	})
	return file_proto_activity_proto_rawDescData
}

var file_proto_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_activity_proto_goTypes = []any{
	(*CourseStats)(nil),           // 0: activity.CourseStats
	(*GetCourseStatsRequest)(nil), // 1: activity.GetCourseStatsRequest
	(*RecordViewRequest)(nil),     // 2: activity.RecordViewRequest
	(*RecordViewResponse)(nil),    // 3: activity.RecordViewResponse
	(*CourseStatsResponse)(nil),   // 4: activity.CourseStatsResponse
}
var file_proto_activity_proto_depIdxs = []int32{
	0, // 0: activity.CourseStatsResponse.stats:type_name -> activity.CourseStats
	1, // 1: activity.ActivityService.GetCourseStats:input_type -> activity.GetCourseStatsRequest
	2, // 2: activity.ActivityService.RecordView:input_type -> activity.RecordViewRequest
	4, // 3: activity.ActivityService.GetCourseStats:output_type -> activity.CourseStatsResponse
	3, // 4: activity.ActivityService.RecordView:output_type -> activity.RecordViewResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_activity_proto_init() }
func file_proto_activity_proto_init() {
	if File_proto_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_activity_proto_rawDesc), len(file_proto_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_activity_proto_goTypes,
		DependencyIndexes: file_proto_activity_proto_depIdxs,
		MessageInfos:      file_proto_activity_proto_msgTypes,
	}.Build()
	File_proto_activity_proto = out.File
	file_proto_activity_proto_goTypes = nil
	file_proto_activity_proto_depIdxs = nil
}
